name: CI
# This workflow is triggered on pushes to the repository.
on: [push, pull_request]

jobs:
  ci:
   runs-on: ${{ matrix.os }}
   
   strategy:
    matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest] ## add different compilers

   steps:
   - name: Install Dependencies (Linux)
     run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository -y ppa:beineri/opt-qt-5.14.0-bionic
          sudo apt-get update -qq
          sudo apt-get install -y -qq gcc g++ cmake qt514base mesa-common-dev libgl1-mesa-dev
     if: matrix.os == 'ubuntu-latest'    
   - name: Install Dependencies (macOS)
     run: |
          brew update && brew install pkgconfig qt5 cmake
     if: matrix.os == 'macOS-latest'     
   - name: Install Dependencies (Windows)
     run: |
          choco install pkgconfig qt5 cmake
     if: matrix.os == 'windows-latest'   
   - name: Get Sources
     uses: actions/checkout@v2
     with:
       submodules: 'true'        
   - name: Setup CMake
     run: |
        mkdir "${{ runner.workspace }}/Build" 
        cd "${{ runner.workspace }}/Build" 
        cmake ${{ runner.workspace }}/../PolyDock
     shell: bash
   - name: Build
     run: cmake --build .
     working-directory: ${{ runner.workspace }}/Build     
   - name: Test
     run: ./Tests
     working-directory: ${{ runner.workspace }}/Dist    
   - name: Check with clang-tidy
     uses: muxee/clang-tidy-action@0.0.1-rc1
