name: CI
# This workflow is triggered on pushes to the repository.
on: push

jobs:
  ci:
   name: ${{ matrix.name }}
   runs-on: ${{ matrix.os }}
  

   strategy:
    matrix:
        os: [ubuntu-18.04]

   steps:
   - uses: actions/checkout@v2
     with:
       submodules: 'true'

   - name: Install (Linux)
     run: |
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository -y ppa:beineri/opt-qt-5.14.0-bionic
        sudo apt-get update -qq
        sudo apt-get install -y -qq gcc g++ cmake qt514base mesa-common-dev libgl1-mesa-dev
        
   - name: config
     run: mkdir Build && cd Build && cmake ../PolyDock
   - name: build
     run: cd Build && make
   - name: clang-tidy check
     uses: muxee/clang-tidy-action@0.0.1-rc1
   # Tests commented out for now - not needed yet.
   #- name: tests
   #  run: ./Dist/Tests

#  build_macos:
#   runs-on: [macos-latest]
  
 # build_windows:
  #  runs-on: [windows-latest]

